FROM mhart/alpine-node:12

# add missing dependencies
RUN apk update \
    && apk add bash \
    && apk add --no-cache --virtual testrun \
        make \
        g++ \
        pango-dev \
        cairo-dev \
        pixman-dev \
        pkgconf \
        libjpeg-turbo-dev \
        python

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install app dependencies
COPY package.json /usr/src/app/
RUN yarn install

# bundle app source
COPY . /usr/src/app

CMD ["yarn", "test"]
